### PR TITLE
Update bankAccount.js

### PR DESCRIPTION
**Pull request by bello123**

### CODE REVIEW

**Comment by bello123** [comment]
Changes made to the BankAccount Class

**Comment by joshuaunity** [comment]
Did you run your code before submitting? you realize your code doesn't work right?

**Comment by joshuaunity** [comment]
I just want to add something which i saw in your code, specifically line 40 and 51, those function calls are not needed as the first and last name will be updated even with out that, you can test this out yourself.

also i want to commend you for going the extra mile as to add a name update feature

**Review by joshuaunity — COMMENTED** [review]
Fantastic Job

**Pull request merged**
